project:
  type: book
  output-dir: docs
  
book:
  title: "learning diary"
  author: "Zhongzhen Ouyang"
  date: "2024/2/1"
  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd
    - week5.qmd
    - week6.qmd
    - week7.qmd
    - week8.qmd
    - references.qmd

bibliography: remote_Sensing_homework.bib

format:
  html:
    theme: cosmo
    cite-method: biblatex

  pdf:
    documentclass: scrreprt
    



