project:
  type: book
  output-dir: docs
book:
  title: "learning diary"
  author: "Zhongzhen Ouyang"
  date: "2024/2/1"
  chapters:
    - index.qmd
    - intro.qmd
    - week1.qmd
    - week3.qmd
    - week5.qmd
    - week6.qmd
    - week7.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



