---
title: "Week 8 - SAR"
---

### Summary

#### Synthetic Aperture Radar: SAR
- Active sensors
- Have surface texture data
- See through weather and clouds
- Different wavelengths - different applications
- SAR utilizes radar beams to transmit and receive signals, measuring the echoes to obtain surface information. Unlike optical sensors, SAR can operate in any weather conditions and can work at night and under cloud cover.
- SAR can collect data in various polarization modes, including single polarization (HH or VV) dual polarization (HH/VV or HH/HV), and fully polarized. Different polarization modes provide different information suitable for various applications.
- VV = surface roughness
VH = volume of surface 
Rough scattering (e.g. bare earth) = most sensitive to VV
Volume scattering (e.g. leaves) = cross, VH or HV
Double bounce (e.g. trees / buildings) = most sensitive to HH.
- A SAR signal has both amplitude (backscatter) and phase data

#### INSAR & DInSAR
- Interferometric synthetic aperture radar (InSAR) techniques combine two or more SAR images over the same region to reveal surface topography or surface motion
- Differential Interferometric Synthetic Aperture Radar (DInSAR): remove the effect of natural elevation
- SAR = active sensor, see through clouds, records energy reflected back

- InSAR = used for DEMs, converting phase different to relative height

- DInSAR = changes between two images in time. Looking at movement of land (uplift or sinking) with topography removed (using a DEM)

#### Identifying change
- Blast Damage Assessment(t-test)

### Application

In the practical, based on Sentinel-1 SAR image, I devised a specialized change detection algorithm designed to perform a pixelwise t-test aimed at identifying alterations arising from the 2020 explosion incident in the port of Beirut.

According to 'LAND COVER MAPPING USING SENTINEL-1 SAR DATA'(Abdikan et al., 2016), this paper investigates the potential of using free-of-charge Sentinel-1 Synthetic Aperture Radar (SAR) imagery for urban land cover classification. They utilized dual-pol (VV+VH) Interferometric Wide swath mode (IW) data collected on September 16th, 2015, over the megacity of Istanbul, Turkey. The Support Vector Machines (SVM) method was employed for classification based on different combinations of VV and VH polarizations, and the results of each combination were evaluated. Their conclusion is that dual-polarimetric Sentinel-1 SAR data can be effectively utilized for generating accurate land cover classification maps, offering significant advantages for urban planning and management of large cities.

### Reflection
This week's SAR section was already introduced during the PowerPoint presentation and group discussion in the second week. At that time, I realized the wide-ranging applications of SAR in remote sensing. The aspect of change detection is particularly intriguing, especially with this week's practical on Blast Damage Assessment, along with Ollie's lecture sharing about monitoring war destruction. It makes me appreciate the significant importance of SAR in post-war recovery and aiding victims. I am glad that the knowledge I've gained in remote sensing can contribute to reducing the impact of devastating conflicts.